name: EndReset
version: 1.0.2
api-version: 1.17
main: pl1.darkermatter.EndReset
author: DarkerMatter
description: Resets Elytras and End Cities in the End dimension
website: https://darker.systems
documentation: https://docs.darker.systems

commands:
  endreset:
    description: Resets Elytras in the End dimension
    usage: /<command>
    permission: endreset.command
  resetelytras:
    description: Resets Elytras in the End dimension
    usage: /<command>
    permission: resetelytras.command

permissions:
  endreset.command:
    description: Allows using the /endreset command
    default: op
  resetelytras.command:
    description: Allows using the /resetelytras command
    default: op
